# Generated by Django 4.2.19 on 2025-08-29 21:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bloomly', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roslina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=200, verbose_name='Nazwa własna')),
                ('gatunek', models.CharField(help_text='np. Monstera deliciosa', max_length=200, verbose_name='Gatunek')),
                ('kategoria', models.CharField(choices=[('doniczkowa', 'Roślina doniczkowa'), ('ogrodowa', 'Roślina ogrodowa'), ('balkonowa', 'Roślina balkonowa'), ('ziolowa', 'Roślina ziołowa'), ('kaktus', 'Kaktus/Sukulenta')], max_length=20, verbose_name='Kategoria')),
                ('poziom_trudnosci', models.CharField(choices=[('latwy', 'Łatwy'), ('sredni', 'Średni'), ('trudny', 'Trudny')], default='sredni', max_length=10, verbose_name='Poziom trudności')),
                ('data_zakupu', models.DateField(verbose_name='Data zakupu/otrzymania')),
                ('data_dodania', models.DateTimeField(auto_now_add=True, verbose_name='Data dodania do aplikacji')),
                ('lokalizacja', models.CharField(blank=True, help_text='np. salon, balkon, kuchnia', max_length=100, verbose_name='Lokalizacja')),
                ('notatki', models.TextField(blank=True, verbose_name='Notatki')),
                ('zdjecie', models.ImageField(blank=True, null=True, upload_to='rosliny/', verbose_name='Zdjęcie')),
                ('czestotliwosc_podlewania', models.IntegerField(default=7, verbose_name='Częstotliwość podlewania (dni)')),
                ('ostatnie_podlewanie', models.DateField(blank=True, null=True, verbose_name='Ostatnie podlewanie')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktywna')),
                ('wlasciciel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Właściciel')),
            ],
            options={
                'verbose_name': 'Roślina',
                'verbose_name_plural': 'Rośliny',
                'ordering': ['-data_dodania'],
            },
        ),
        migrations.CreateModel(
            name='CzynoscPielegnacyjna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ', models.CharField(choices=[('podlewanie', 'Podlewanie'), ('nawozenie', 'Nawożenie'), ('przycinanie', 'Przycinanie'), ('przesadzanie', 'Przesadzanie'), ('oprysklowanie', 'Oprysklowanie'), ('inne', 'Inne')], max_length=20, verbose_name='Typ czynności')),
                ('data', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data wykonania')),
                ('wykonane', models.BooleanField(default=True, verbose_name='Wykonane')),
                ('notatki', models.TextField(blank=True, verbose_name='Notatki')),
                ('zdjecie', models.ImageField(blank=True, null=True, upload_to='czynnosci/', verbose_name='Zdjęcie')),
                ('roslina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bloomly.roslina', verbose_name='Roślina')),
                ('uzytkownik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik')),
            ],
            options={
                'verbose_name': 'Czynność pielęgnacyjna',
                'verbose_name_plural': 'Czynności pielęgnacyjne',
                'ordering': ['-data'],
            },
        ),
    ]
