# Generated by Django 4.2.19 on 2025-08-31 14:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bloomly', '0002_roslina_czynoscpielegnacyjna'),
    ]

    operations = [
        migrations.CreateModel(
            name='Przypomnienie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ', models.CharField(choices=[('podlewanie', 'Podlewanie'), ('nawozenie', 'Nawożenie'), ('przycinanie', 'Przycinanie'), ('przesadzanie', 'Przesadzanie'), ('ogolne', 'Ogólne przypomnienie')], max_length=20, verbose_name='Typ przypomnienia')),
                ('tytul', models.CharField(max_length=200, verbose_name='Tytuł')),
                ('tresc', models.TextField(verbose_name='Treść przypomnienia')),
                ('data_przypomnienia', models.DateTimeField(verbose_name='Data przypomnienia')),
                ('data_utworzenia', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
                ('data_wyslania', models.DateTimeField(blank=True, null=True, verbose_name='Data wysłania')),
                ('data_wykonania', models.DateTimeField(blank=True, null=True, verbose_name='Data wykonania')),
                ('status', models.CharField(choices=[('oczekujace', 'Oczekujące'), ('wyslane', 'Wysłane'), ('wykonane', 'Wykonane'), ('odlozone', 'Odłożone'), ('anulowane', 'Anulowane')], default='oczekujace', max_length=20, verbose_name='Status')),
                ('wyslane', models.BooleanField(default=False, verbose_name='Wysłane')),
                ('powtarzalne', models.BooleanField(default=False, verbose_name='Powtarzalne')),
                ('interwal_dni', models.IntegerField(blank=True, null=True, verbose_name='Interwał (dni)')),
                ('automatyczne', models.BooleanField(default=False, verbose_name='Utworzone automatycznie')),
                ('priorytet', models.IntegerField(default=1, verbose_name='Priorytet (1-5)')),
                ('roslina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bloomly.roslina', verbose_name='Roślina')),
                ('uzytkownik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik')),
            ],
            options={
                'verbose_name': 'Przypomnienie',
                'verbose_name_plural': 'Przypomnienia',
                'ordering': ['data_przypomnienia'],
            },
        ),
    ]
