# Generated by Django 4.2.19 on 2025-09-29 15:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bloomly', '0003_przypomnienie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100, verbose_name='Nazwa kategorii')),
                ('slug', models.SlugField(unique=True, verbose_name='URL slug')),
                ('opis', models.TextField(blank=True, verbose_name='Opis')),
                ('typ', models.CharField(choices=[('forum', 'Forum'), ('baza', 'Baza wiedzy')], default='forum', max_length=10, verbose_name='Typ')),
                ('ikona', models.CharField(blank=True, help_text='np. bi-chat, bi-book', max_length=50, verbose_name='Ikona Bootstrap')),
                ('kolejnosc', models.IntegerField(default=0, verbose_name='Kolejność wyświetlania')),
                ('aktywna', models.BooleanField(default=True, verbose_name='Aktywna')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rodzic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='podkategorie', to='bloomly.kategoria', verbose_name='Kategoria nadrzędna')),
            ],
            options={
                'verbose_name': 'Kategoria',
                'verbose_name_plural': 'Kategorie',
                'ordering': ['kolejnosc', 'nazwa'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tytul', models.CharField(max_length=200, verbose_name='Tytuł')),
                ('slug', models.SlugField(unique=True, verbose_name='URL slug')),
                ('tresc', models.TextField(verbose_name='Treść')),
                ('status', models.CharField(choices=[('draft', 'Szkic'), ('published', 'Opublikowany'), ('archived', 'Zarchiwizowany')], default='published', max_length=20, verbose_name='Status')),
                ('wyrozniany', models.BooleanField(default=False, verbose_name='Wyróżniony')),
                ('zablokowany', models.BooleanField(default=False, verbose_name='Zablokowany (brak komentarzy)')),
                ('zdjecie_glowne', models.ImageField(blank=True, null=True, upload_to='posty/', verbose_name='Zdjęcie główne')),
                ('wyswietlenia', models.IntegerField(default=0, verbose_name='Wyświetlenia')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data aktualizacji')),
                ('opublikowany_at', models.DateTimeField(blank=True, null=True, verbose_name='Data publikacji')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('kategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bloomly.kategoria', verbose_name='Kategoria')),
                ('polubienia', models.ManyToManyField(blank=True, related_name='polubione_posty', to=settings.AUTH_USER_MODEL, verbose_name='Polubienia')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posty',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Komentarz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tresc', models.TextField(verbose_name='Treść komentarza')),
                ('zatwierdzony', models.BooleanField(default=True, verbose_name='Zatwierdzony')),
                ('zgloszone', models.BooleanField(default=False, verbose_name='Zgłoszony przez użytkowników')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data edycji')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('polubienia', models.ManyToManyField(blank=True, related_name='polubione_komentarze', to=settings.AUTH_USER_MODEL, verbose_name='Polubienia')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bloomly.post', verbose_name='Post')),
                ('rodzic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='odpowiedzi', to='bloomly.komentarz', verbose_name='Komentarz nadrzędny')),
            ],
            options={
                'verbose_name': 'Komentarz',
                'verbose_name_plural': 'Komentarze',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='BazaRoslin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa_polska', models.CharField(max_length=200, verbose_name='Nazwa polska')),
                ('nazwa_naukowa', models.CharField(max_length=200, verbose_name='Nazwa naukowa (łacińska)')),
                ('slug', models.SlugField(unique=True, verbose_name='URL slug')),
                ('opis_krotki', models.TextField(max_length=500, verbose_name='Krótki opis')),
                ('opis_szczegolowy', models.TextField(verbose_name='Szczegółowy opis')),
                ('rodzina', models.CharField(blank=True, max_length=100, verbose_name='Rodzina botaniczna')),
                ('rodzaj', models.CharField(blank=True, max_length=100, verbose_name='Rodzaj')),
                ('poziom_trudnosci', models.CharField(choices=[('latwy', 'Łatwy'), ('sredni', 'Średni'), ('trudny', 'Trudny')], max_length=10, verbose_name='Poziom trudności')),
                ('wymagania_swiatla', models.CharField(help_text='np. pełne słońce, półcień', max_length=100, verbose_name='Wymagania świetlne')),
                ('czestotliwosc_podlewania', models.CharField(max_length=100, verbose_name='Częstotliwość podlewania')),
                ('wilgotnosc_powietrza', models.CharField(blank=True, max_length=100, verbose_name='Wilgotność powietrza')),
                ('temperatura_min', models.IntegerField(blank=True, null=True, verbose_name='Temperatura minimalna (°C)')),
                ('temperatura_max', models.IntegerField(blank=True, null=True, verbose_name='Temperatura maksymalna (°C)')),
                ('podloz', models.CharField(blank=True, max_length=200, verbose_name='Typ podłoża')),
                ('nawozenie', models.TextField(blank=True, verbose_name='Nawożenie')),
                ('rozmnazanie', models.TextField(blank=True, verbose_name='Rozmnażanie')),
                ('choroby_szkodniki', models.TextField(blank=True, verbose_name='Choroby i szkodniki')),
                ('ciekawostki', models.TextField(blank=True, verbose_name='Ciekawostki')),
                ('toksyczna_dla_ludzi', models.BooleanField(default=False, verbose_name='Toksyczna dla ludzi')),
                ('toksyczna_dla_zwierzat', models.BooleanField(default=False, verbose_name='Toksyczna dla zwierząt')),
                ('zdjecie_glowne', models.ImageField(blank=True, null=True, upload_to='baza_roslin/', verbose_name='Zdjęcie główne')),
                ('zweryfikowane', models.BooleanField(default=False, verbose_name='Zweryfikowane przez eksperta')),
                ('wyswietlenia', models.IntegerField(default=0, verbose_name='Wyświetlenia')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Dodane przez')),
            ],
            options={
                'verbose_name': 'Roślina w bazie wiedzy',
                'verbose_name_plural': 'Baza wiedzy - rośliny',
                'ordering': ['nazwa_polska'],
            },
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['kategoria', 'status'], name='bloomly_pos_kategor_d1f442_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['autor'], name='bloomly_pos_autor_i_cd15f0_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['-created_at'], name='bloomly_pos_created_167f07_idx'),
        ),
        migrations.AddIndex(
            model_name='bazaroslin',
            index=models.Index(fields=['nazwa_polska'], name='bloomly_baz_nazwa_p_e3b32b_idx'),
        ),
        migrations.AddIndex(
            model_name='bazaroslin',
            index=models.Index(fields=['nazwa_naukowa'], name='bloomly_baz_nazwa_n_f12176_idx'),
        ),
    ]
