# Generated by Django 4.2.19 on 2025-10-04 11:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bloomly', '0004_kategoria_post_komentarz_bazaroslin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalizaPielegnacji',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('srednia_czestotliwosc_dni', models.FloatField(verbose_name='Średnia częstotliwość (dni)')),
                ('odchylenie_standardowe', models.FloatField(default=0, verbose_name='Odchylenie standardowe')),
                ('liczba_podlan', models.IntegerField(default=0, verbose_name='Liczba podlań')),
                ('srednia_temperatura', models.FloatField(blank=True, null=True, verbose_name='Średnia temperatura')),
                ('srednia_wilgotnosc', models.FloatField(blank=True, null=True, verbose_name='Średnia wilgotność')),
                ('podlewa_rano', models.BooleanField(default=False, verbose_name='Podlewa rano (6-12)')),
                ('podlewa_po_poludniu', models.BooleanField(default=False, verbose_name='Podlewa po południu (12-18)')),
                ('podlewa_wieczorem', models.BooleanField(default=False, verbose_name='Podlewa wieczorem (18-24)')),
                ('rekomendowana_czestotliwosc', models.IntegerField(blank=True, null=True, verbose_name='Rekomendowana częstotliwość (dni)')),
                ('pewnosc_rekomendacji', models.FloatField(default=0, verbose_name='Pewność rekomendacji (0-1)')),
                ('ostatnia_analiza', models.DateTimeField(auto_now=True, verbose_name='Data ostatniej analizy')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('roslina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bloomly.roslina', verbose_name='Roślina')),
                ('uzytkownik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik')),
            ],
            options={
                'verbose_name': 'Analiza pielęgnacji',
                'verbose_name_plural': 'Analizy pielęgnacji',
                'unique_together': {('roslina', 'uzytkownik')},
            },
        ),
    ]
