# Generated by Django 4.2.23 on 2025-10-22 00:03

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bloomly', '0005_analizapielegnacji'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analizapielegnacji',
            options={'verbose_name': 'Analiza Pielęgnacji', 'verbose_name_plural': 'Analizy Pielęgnacji'},
        ),
        migrations.AlterUniqueTogether(
            name='analizapielegnacji',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='analizapielegnacji',
            name='ostatnia_aktualizacja',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='analizapielegnacji',
            name='utworzono',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 10, 22, 0, 3, 8, 637575, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='analizapielegnacji',
            name='liczba_podlan',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='analizapielegnacji',
            name='odchylenie_standardowe',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='analizapielegnacji',
            name='pewnosc_rekomendacji',
            field=models.FloatField(default=0.5),
        ),
        migrations.AlterField(
            model_name='analizapielegnacji',
            name='podlewa_po_poludniu',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='analizapielegnacji',
            name='podlewa_rano',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='analizapielegnacji',
            name='podlewa_wieczorem',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='analizapielegnacji',
            name='rekomendowana_czestotliwosc',
            field=models.IntegerField(default=7),
        ),
        migrations.AlterField(
            model_name='analizapielegnacji',
            name='roslina',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analiza', to='bloomly.roslina'),
        ),
        migrations.AlterField(
            model_name='analizapielegnacji',
            name='srednia_czestotliwosc_dni',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='analizapielegnacji',
            name='uzytkownik',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='analizapielegnacji',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='analizapielegnacji',
            name='ostatnia_analiza',
        ),
        migrations.RemoveField(
            model_name='analizapielegnacji',
            name='srednia_temperatura',
        ),
        migrations.RemoveField(
            model_name='analizapielegnacji',
            name='srednia_wilgotnosc',
        ),
    ]
