# Generated by Django 4.2.23 on 2025-10-25 23:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bloomly', '0006_alter_analizapielegnacji_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiluzytkownika',
            name='biogram',
            field=models.TextField(blank=True, max_length=600),
        ),
        migrations.AlterField(
            model_name='profiluzytkownika',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AlterField(
            model_name='profiluzytkownika',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profiluzytkownika', to=settings.AUTH_USER_MODEL),
        ),
    ]
