# Generated by Django 4.2.23 on 2025-11-05 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloomly', '0007_profiluzytkownika_biogram_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='czynoscpielegnacyjna',
            name='ilosc_wody',
            field=models.CharField(blank=True, choices=[('low', 'mało'), ('med', 'średnio'), ('high', 'dużo')], max_length=8, null=True, verbose_name='Ilość wody'),
        ),
        migrations.AddField(
            model_name='czynoscpielegnacyjna',
            name='interwal_dni',
            field=models.FloatField(blank=True, null=True, verbose_name='Interwał od poprzedniego (dni)'),
        ),
        migrations.AddField(
            model_name='czynoscpielegnacyjna',
            name='stan_gleby',
            field=models.CharField(blank=True, choices=[('dry', 'sucha'), ('moist', 'lekko wilgotna'), ('wet', 'mokra')], max_length=8, null=True, verbose_name='Stan gleby'),
        ),
    ]
