# Generated by Django 4.2.23 on 2025-11-09 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloomly', '0008_czynoscpielegnacyjna_ilosc_wody_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roslina',
            name='kategoria',
            field=models.CharField(choices=[('doniczkowa', 'Roślina doniczkowa'), ('ogrodowa', 'Roślina ogrodowa'), ('balkonowa', 'Roślina balkonowa'), ('ziolowa', 'Roślina ziołowa')], max_length=20, verbose_name='Kategoria'),
        ),
    ]
