# Generated by Django 4.2.23 on 2025-11-19 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloomly', '0009_alter_roslina_kategoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='komentarz',
            name='polubienia',
        ),
        migrations.RemoveField(
            model_name='komentarz',
            name='rodzic',
        ),
        migrations.RemoveField(
            model_name='komentarz',
            name='zatwierdzony',
        ),
        migrations.RemoveField(
            model_name='komentarz',
            name='zgloszone',
        ),
        migrations.RemoveField(
            model_name='post',
            name='opublikowany_at',
        ),
        migrations.RemoveField(
            model_name='post',
            name='polubienia',
        ),
        migrations.RemoveField(
            model_name='post',
            name='wyrozniany',
        ),
        migrations.RemoveField(
            model_name='post',
            name='zdjecie_glowne',
        ),
        migrations.RemoveField(
            model_name='profiluzytkownika',
            name='powiadomienia_sms',
        ),
        migrations.AlterField(
            model_name='czynoscpielegnacyjna',
            name='typ',
            field=models.CharField(choices=[('podlewanie', 'Podlewanie'), ('nawozenie', 'Nawożenie'), ('przycinanie', 'Przycinanie'), ('przesadzanie', 'Przesadzanie')], max_length=20, verbose_name='Typ czynności'),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('published', 'Opublikowany')], default='published', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='przypomnienie',
            name='automatyczne',
            field=models.BooleanField(default=True, verbose_name='Utworzone automatycznie'),
        ),
        migrations.AlterField(
            model_name='przypomnienie',
            name='interwal_dni',
            field=models.IntegerField(blank=True, null=True, verbose_name='Interwał (dni) wg ML'),
        ),
        migrations.AlterField(
            model_name='przypomnienie',
            name='powtarzalne',
            field=models.BooleanField(default=True, verbose_name='Systemowe (ML)'),
        ),
        migrations.AlterField(
            model_name='przypomnienie',
            name='status',
            field=models.CharField(choices=[('oczekujace', 'Oczekujące'), ('wykonane', 'Wykonane')], default='oczekujace', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='przypomnienie',
            name='typ',
            field=models.CharField(choices=[('podlewanie', 'Podlewanie')], default='podlewanie', max_length=20, verbose_name='Typ przypomnienia'),
        ),
    ]
