# Generated by Django 4.2.23 on 2025-11-19 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloomly', '0010_remove_komentarz_polubienia_remove_komentarz_rodzic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='opublikowany_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
