# Generated by Django 4.2.23 on 2025-11-24 17:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloomly', '0011_post_opublikowany_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analizapielegnacji',
            name='ostatnia_aktualizacja',
        ),
        migrations.RemoveField(
            model_name='analizapielegnacji',
            name='utworzono',
        ),
        migrations.AddField(
            model_name='analizapielegnacji',
            name='cv_mae',
            field=models.FloatField(blank=True, null=True, verbose_name='CV MAE (Cross-Validation)'),
        ),
        migrations.AddField(
            model_name='analizapielegnacji',
            name='data_aktualizacji',
            field=models.DateTimeField(auto_now=True, verbose_name='Ostatnia aktualizacja'),
        ),
        migrations.AddField(
            model_name='analizapielegnacji',
            name='data_utworzenia',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 11, 24, 17, 33, 32, 93020, tzinfo=datetime.timezone.utc), verbose_name='Data utworzenia'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='analizapielegnacji',
            name='mae',
            field=models.FloatField(blank=True, null=True, verbose_name='MAE (Mean Absolute Error)'),
        ),
        migrations.AddField(
            model_name='analizapielegnacji',
            name='pewnosc_biologia',
            field=models.FloatField(default=0.0, verbose_name='Pewność - zgodność biologiczna'),
        ),
        migrations.AddField(
            model_name='analizapielegnacji',
            name='pewnosc_model',
            field=models.FloatField(default=0.0, verbose_name='Pewność - jakość modelu'),
        ),
        migrations.AddField(
            model_name='analizapielegnacji',
            name='pewnosc_regularnosc',
            field=models.FloatField(default=0.0, verbose_name='Pewność - regularność'),
        ),
        migrations.AddField(
            model_name='analizapielegnacji',
            name='r2_score',
            field=models.FloatField(blank=True, null=True, verbose_name='R² Score'),
        ),
        migrations.AddField(
            model_name='analizapielegnacji',
            name='rmse',
            field=models.FloatField(blank=True, null=True, verbose_name='RMSE'),
        ),
        migrations.AddField(
            model_name='analizapielegnacji',
            name='typ_modelu',
            field=models.CharField(choices=[('RF', 'Random Forest'), ('GB', 'Gradient Boosting')], default='RF', max_length=2, verbose_name='Typ modelu ML'),
        ),
    ]
